// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime.proto

#include "runtime.pb.h"
#include "runtime.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace helixrt {

static const char* RuntimeService_method_names[] = {
  "/helixrt.RuntimeService/StartRuntime",
  "/helixrt.RuntimeService/StopRuntime",
  "/helixrt.RuntimeService/StreamMetrics",
  "/helixrt.RuntimeService/SetSchedulerMode",
};

std::unique_ptr< RuntimeService::Stub> RuntimeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RuntimeService::Stub> stub(new RuntimeService::Stub(channel));
  return stub;
}

RuntimeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartRuntime_(RuntimeService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopRuntime_(RuntimeService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamMetrics_(RuntimeService_method_names[2], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SetSchedulerMode_(RuntimeService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RuntimeService::Stub::StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::helixrt::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartRuntime_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartRuntime_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartRuntime_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartRuntime_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartRuntime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::AsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_StartRuntime_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::PrepareAsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_StartRuntime_, context, request, false);
}

::grpc::Status RuntimeService::Stub::StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::helixrt::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopRuntime_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopRuntime_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopRuntime_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopRuntime_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopRuntime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::AsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_StopRuntime_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::PrepareAsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_StopRuntime_, context, request, false);
}

::grpc::ClientReader< ::helixrt::RuntimeMetrics>* RuntimeService::Stub::StreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::helixrt::RuntimeMetrics>::Create(channel_.get(), rpcmethod_StreamMetrics_, context, request);
}

void RuntimeService::Stub::experimental_async::StreamMetrics(::grpc::ClientContext* context, ::helixrt::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::helixrt::RuntimeMetrics>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::helixrt::RuntimeMetrics>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamMetrics_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>* RuntimeService::Stub::AsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::helixrt::RuntimeMetrics>::Create(channel_.get(), cq, rpcmethod_StreamMetrics_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>* RuntimeService::Stub::PrepareAsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::helixrt::RuntimeMetrics>::Create(channel_.get(), cq, rpcmethod_StreamMetrics_, context, request, false, nullptr);
}

::grpc::Status RuntimeService::Stub::SetSchedulerMode(::grpc::ClientContext* context, const ::helixrt::SetSchedulerRequest& request, ::helixrt::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetSchedulerMode_, context, request, response);
}

void RuntimeService::Stub::experimental_async::SetSchedulerMode(::grpc::ClientContext* context, const ::helixrt::SetSchedulerRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetSchedulerMode_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::SetSchedulerMode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SetSchedulerMode_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::SetSchedulerMode(::grpc::ClientContext* context, const ::helixrt::SetSchedulerRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetSchedulerMode_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::SetSchedulerMode(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SetSchedulerMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::AsyncSetSchedulerModeRaw(::grpc::ClientContext* context, const ::helixrt::SetSchedulerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_SetSchedulerMode_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* RuntimeService::Stub::PrepareAsyncSetSchedulerModeRaw(::grpc::ClientContext* context, const ::helixrt::SetSchedulerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helixrt::StatusResponse>::Create(channel_.get(), cq, rpcmethod_SetSchedulerMode_, context, request, false);
}

RuntimeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::helixrt::StartRequest, ::helixrt::StatusResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::helixrt::StartRequest* req,
             ::helixrt::StatusResponse* resp) {
               return service->StartRuntime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::helixrt::StopRequest, ::helixrt::StatusResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::helixrt::StopRequest* req,
             ::helixrt::StatusResponse* resp) {
               return service->StopRuntime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RuntimeService::Service, ::helixrt::StreamRequest, ::helixrt::RuntimeMetrics>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::helixrt::StreamRequest* req,
             ::grpc_impl::ServerWriter<::helixrt::RuntimeMetrics>* writer) {
               return service->StreamMetrics(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::helixrt::SetSchedulerRequest, ::helixrt::StatusResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::helixrt::SetSchedulerRequest* req,
             ::helixrt::StatusResponse* resp) {
               return service->SetSchedulerMode(ctx, req, resp);
             }, this)));
}

RuntimeService::Service::~Service() {
}

::grpc::Status RuntimeService::Service::StartRuntime(::grpc::ServerContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StopRuntime(::grpc::ServerContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StreamMetrics(::grpc::ServerContext* context, const ::helixrt::StreamRequest* request, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::SetSchedulerMode(::grpc::ServerContext* context, const ::helixrt::SetSchedulerRequest* request, ::helixrt::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helixrt

