// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_runtime_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_runtime_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_runtime_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_runtime_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_runtime_2eproto;
namespace helixrt {
class RuntimeMetrics;
class RuntimeMetricsDefaultTypeInternal;
extern RuntimeMetricsDefaultTypeInternal _RuntimeMetrics_default_instance_;
class StartRequest;
class StartRequestDefaultTypeInternal;
extern StartRequestDefaultTypeInternal _StartRequest_default_instance_;
class StatusResponse;
class StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
class StopRequest;
class StopRequestDefaultTypeInternal;
extern StopRequestDefaultTypeInternal _StopRequest_default_instance_;
class StreamRequest;
class StreamRequestDefaultTypeInternal;
extern StreamRequestDefaultTypeInternal _StreamRequest_default_instance_;
}  // namespace helixrt
PROTOBUF_NAMESPACE_OPEN
template<> ::helixrt::RuntimeMetrics* Arena::CreateMaybeMessage<::helixrt::RuntimeMetrics>(Arena*);
template<> ::helixrt::StartRequest* Arena::CreateMaybeMessage<::helixrt::StartRequest>(Arena*);
template<> ::helixrt::StatusResponse* Arena::CreateMaybeMessage<::helixrt::StatusResponse>(Arena*);
template<> ::helixrt::StopRequest* Arena::CreateMaybeMessage<::helixrt::StopRequest>(Arena*);
template<> ::helixrt::StreamRequest* Arena::CreateMaybeMessage<::helixrt::StreamRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace helixrt {

// ===================================================================

class StartRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helixrt.StartRequest) */ {
 public:
  inline StartRequest() : StartRequest(nullptr) {};
  virtual ~StartRequest();

  StartRequest(const StartRequest& from);
  StartRequest(StartRequest&& from) noexcept
    : StartRequest() {
    *this = ::std::move(from);
  }

  inline StartRequest& operator=(const StartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartRequest& operator=(StartRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StartRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartRequest* internal_default_instance() {
    return reinterpret_cast<const StartRequest*>(
               &_StartRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StartRequest& a, StartRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StartRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StartRequest* New() const final {
    return CreateMaybeMessage<StartRequest>(nullptr);
  }

  StartRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StartRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StartRequest& from);
  void MergeFrom(const StartRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StartRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helixrt.StartRequest";
  }
  protected:
  explicit StartRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_runtime_2eproto);
    return ::descriptor_table_runtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuntimeIdFieldNumber = 1,
    kThreadCountFieldNumber = 2,
  };
  // string runtime_id = 1;
  void clear_runtime_id();
  const std::string& runtime_id() const;
  void set_runtime_id(const std::string& value);
  void set_runtime_id(std::string&& value);
  void set_runtime_id(const char* value);
  void set_runtime_id(const char* value, size_t size);
  std::string* mutable_runtime_id();
  std::string* release_runtime_id();
  void set_allocated_runtime_id(std::string* runtime_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_runtime_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_runtime_id(
      std::string* runtime_id);
  private:
  const std::string& _internal_runtime_id() const;
  void _internal_set_runtime_id(const std::string& value);
  std::string* _internal_mutable_runtime_id();
  public:

  // int32 thread_count = 2;
  void clear_thread_count();
  ::PROTOBUF_NAMESPACE_ID::int32 thread_count() const;
  void set_thread_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_thread_count() const;
  void _internal_set_thread_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:helixrt.StartRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr runtime_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 thread_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_runtime_2eproto;
};
// -------------------------------------------------------------------

class StopRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helixrt.StopRequest) */ {
 public:
  inline StopRequest() : StopRequest(nullptr) {};
  virtual ~StopRequest();

  StopRequest(const StopRequest& from);
  StopRequest(StopRequest&& from) noexcept
    : StopRequest() {
    *this = ::std::move(from);
  }

  inline StopRequest& operator=(const StopRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopRequest& operator=(StopRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StopRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopRequest* internal_default_instance() {
    return reinterpret_cast<const StopRequest*>(
               &_StopRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StopRequest& a, StopRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StopRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StopRequest* New() const final {
    return CreateMaybeMessage<StopRequest>(nullptr);
  }

  StopRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StopRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StopRequest& from);
  void MergeFrom(const StopRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helixrt.StopRequest";
  }
  protected:
  explicit StopRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_runtime_2eproto);
    return ::descriptor_table_runtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuntimeIdFieldNumber = 1,
  };
  // string runtime_id = 1;
  void clear_runtime_id();
  const std::string& runtime_id() const;
  void set_runtime_id(const std::string& value);
  void set_runtime_id(std::string&& value);
  void set_runtime_id(const char* value);
  void set_runtime_id(const char* value, size_t size);
  std::string* mutable_runtime_id();
  std::string* release_runtime_id();
  void set_allocated_runtime_id(std::string* runtime_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_runtime_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_runtime_id(
      std::string* runtime_id);
  private:
  const std::string& _internal_runtime_id() const;
  void _internal_set_runtime_id(const std::string& value);
  std::string* _internal_mutable_runtime_id();
  public:

  // @@protoc_insertion_point(class_scope:helixrt.StopRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr runtime_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_runtime_2eproto;
};
// -------------------------------------------------------------------

class StreamRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helixrt.StreamRequest) */ {
 public:
  inline StreamRequest() : StreamRequest(nullptr) {};
  virtual ~StreamRequest();

  StreamRequest(const StreamRequest& from);
  StreamRequest(StreamRequest&& from) noexcept
    : StreamRequest() {
    *this = ::std::move(from);
  }

  inline StreamRequest& operator=(const StreamRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamRequest& operator=(StreamRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StreamRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StreamRequest* internal_default_instance() {
    return reinterpret_cast<const StreamRequest*>(
               &_StreamRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StreamRequest& a, StreamRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StreamRequest* New() const final {
    return CreateMaybeMessage<StreamRequest>(nullptr);
  }

  StreamRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StreamRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StreamRequest& from);
  void MergeFrom(const StreamRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helixrt.StreamRequest";
  }
  protected:
  explicit StreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_runtime_2eproto);
    return ::descriptor_table_runtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuntimeIdFieldNumber = 1,
  };
  // string runtime_id = 1;
  void clear_runtime_id();
  const std::string& runtime_id() const;
  void set_runtime_id(const std::string& value);
  void set_runtime_id(std::string&& value);
  void set_runtime_id(const char* value);
  void set_runtime_id(const char* value, size_t size);
  std::string* mutable_runtime_id();
  std::string* release_runtime_id();
  void set_allocated_runtime_id(std::string* runtime_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_runtime_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_runtime_id(
      std::string* runtime_id);
  private:
  const std::string& _internal_runtime_id() const;
  void _internal_set_runtime_id(const std::string& value);
  std::string* _internal_mutable_runtime_id();
  public:

  // @@protoc_insertion_point(class_scope:helixrt.StreamRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr runtime_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_runtime_2eproto;
};
// -------------------------------------------------------------------

class StatusResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helixrt.StatusResponse) */ {
 public:
  inline StatusResponse() : StatusResponse(nullptr) {};
  virtual ~StatusResponse();

  StatusResponse(const StatusResponse& from);
  StatusResponse(StatusResponse&& from) noexcept
    : StatusResponse() {
    *this = ::std::move(from);
  }

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StatusResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
               &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(StatusResponse& a, StatusResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StatusResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StatusResponse* New() const final {
    return CreateMaybeMessage<StatusResponse>(nullptr);
  }

  StatusResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StatusResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StatusResponse& from);
  void MergeFrom(const StatusResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helixrt.StatusResponse";
  }
  protected:
  explicit StatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_runtime_2eproto);
    return ::descriptor_table_runtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:helixrt.StatusResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_runtime_2eproto;
};
// -------------------------------------------------------------------

class RuntimeMetrics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:helixrt.RuntimeMetrics) */ {
 public:
  inline RuntimeMetrics() : RuntimeMetrics(nullptr) {};
  virtual ~RuntimeMetrics();

  RuntimeMetrics(const RuntimeMetrics& from);
  RuntimeMetrics(RuntimeMetrics&& from) noexcept
    : RuntimeMetrics() {
    *this = ::std::move(from);
  }

  inline RuntimeMetrics& operator=(const RuntimeMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline RuntimeMetrics& operator=(RuntimeMetrics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RuntimeMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RuntimeMetrics* internal_default_instance() {
    return reinterpret_cast<const RuntimeMetrics*>(
               &_RuntimeMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RuntimeMetrics& a, RuntimeMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(RuntimeMetrics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RuntimeMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RuntimeMetrics* New() const final {
    return CreateMaybeMessage<RuntimeMetrics>(nullptr);
  }

  RuntimeMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RuntimeMetrics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RuntimeMetrics& from);
  void MergeFrom(const RuntimeMetrics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RuntimeMetrics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "helixrt.RuntimeMetrics";
  }
  protected:
  explicit RuntimeMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_runtime_2eproto);
    return ::descriptor_table_runtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuntimeIdFieldNumber = 1,
    kThroughputFieldNumber = 3,
    kLatencyFieldNumber = 4,
    kCpuUsageFieldNumber = 5,
    kTimestampFieldNumber = 6,
    kActiveThreadsFieldNumber = 2,
  };
  // string runtime_id = 1;
  void clear_runtime_id();
  const std::string& runtime_id() const;
  void set_runtime_id(const std::string& value);
  void set_runtime_id(std::string&& value);
  void set_runtime_id(const char* value);
  void set_runtime_id(const char* value, size_t size);
  std::string* mutable_runtime_id();
  std::string* release_runtime_id();
  void set_allocated_runtime_id(std::string* runtime_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_runtime_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_runtime_id(
      std::string* runtime_id);
  private:
  const std::string& _internal_runtime_id() const;
  void _internal_set_runtime_id(const std::string& value);
  std::string* _internal_mutable_runtime_id();
  public:

  // double throughput = 3;
  void clear_throughput();
  double throughput() const;
  void set_throughput(double value);
  private:
  double _internal_throughput() const;
  void _internal_set_throughput(double value);
  public:

  // double latency = 4;
  void clear_latency();
  double latency() const;
  void set_latency(double value);
  private:
  double _internal_latency() const;
  void _internal_set_latency(double value);
  public:

  // double cpu_usage = 5;
  void clear_cpu_usage();
  double cpu_usage() const;
  void set_cpu_usage(double value);
  private:
  double _internal_cpu_usage() const;
  void _internal_set_cpu_usage(double value);
  public:

  // int64 timestamp = 6;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 active_threads = 2;
  void clear_active_threads();
  ::PROTOBUF_NAMESPACE_ID::int32 active_threads() const;
  void set_active_threads(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_active_threads() const;
  void _internal_set_active_threads(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:helixrt.RuntimeMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr runtime_id_;
  double throughput_;
  double latency_;
  double cpu_usage_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 active_threads_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_runtime_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartRequest

// string runtime_id = 1;
inline void StartRequest::clear_runtime_id() {
  runtime_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StartRequest::runtime_id() const {
  // @@protoc_insertion_point(field_get:helixrt.StartRequest.runtime_id)
  return _internal_runtime_id();
}
inline void StartRequest::set_runtime_id(const std::string& value) {
  _internal_set_runtime_id(value);
  // @@protoc_insertion_point(field_set:helixrt.StartRequest.runtime_id)
}
inline std::string* StartRequest::mutable_runtime_id() {
  // @@protoc_insertion_point(field_mutable:helixrt.StartRequest.runtime_id)
  return _internal_mutable_runtime_id();
}
inline const std::string& StartRequest::_internal_runtime_id() const {
  return runtime_id_.Get();
}
inline void StartRequest::_internal_set_runtime_id(const std::string& value) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StartRequest::set_runtime_id(std::string&& value) {
  
  runtime_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helixrt.StartRequest.runtime_id)
}
inline void StartRequest::set_runtime_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helixrt.StartRequest.runtime_id)
}
inline void StartRequest::set_runtime_id(const char* value,
    size_t size) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helixrt.StartRequest.runtime_id)
}
inline std::string* StartRequest::_internal_mutable_runtime_id() {
  
  return runtime_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StartRequest::release_runtime_id() {
  // @@protoc_insertion_point(field_release:helixrt.StartRequest.runtime_id)
  return runtime_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StartRequest::set_allocated_runtime_id(std::string* runtime_id) {
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), runtime_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helixrt.StartRequest.runtime_id)
}
inline std::string* StartRequest::unsafe_arena_release_runtime_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helixrt.StartRequest.runtime_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return runtime_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StartRequest::unsafe_arena_set_allocated_runtime_id(
    std::string* runtime_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      runtime_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helixrt.StartRequest.runtime_id)
}

// int32 thread_count = 2;
inline void StartRequest::clear_thread_count() {
  thread_count_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StartRequest::_internal_thread_count() const {
  return thread_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 StartRequest::thread_count() const {
  // @@protoc_insertion_point(field_get:helixrt.StartRequest.thread_count)
  return _internal_thread_count();
}
inline void StartRequest::_internal_set_thread_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  thread_count_ = value;
}
inline void StartRequest::set_thread_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_thread_count(value);
  // @@protoc_insertion_point(field_set:helixrt.StartRequest.thread_count)
}

// -------------------------------------------------------------------

// StopRequest

// string runtime_id = 1;
inline void StopRequest::clear_runtime_id() {
  runtime_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StopRequest::runtime_id() const {
  // @@protoc_insertion_point(field_get:helixrt.StopRequest.runtime_id)
  return _internal_runtime_id();
}
inline void StopRequest::set_runtime_id(const std::string& value) {
  _internal_set_runtime_id(value);
  // @@protoc_insertion_point(field_set:helixrt.StopRequest.runtime_id)
}
inline std::string* StopRequest::mutable_runtime_id() {
  // @@protoc_insertion_point(field_mutable:helixrt.StopRequest.runtime_id)
  return _internal_mutable_runtime_id();
}
inline const std::string& StopRequest::_internal_runtime_id() const {
  return runtime_id_.Get();
}
inline void StopRequest::_internal_set_runtime_id(const std::string& value) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StopRequest::set_runtime_id(std::string&& value) {
  
  runtime_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helixrt.StopRequest.runtime_id)
}
inline void StopRequest::set_runtime_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helixrt.StopRequest.runtime_id)
}
inline void StopRequest::set_runtime_id(const char* value,
    size_t size) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helixrt.StopRequest.runtime_id)
}
inline std::string* StopRequest::_internal_mutable_runtime_id() {
  
  return runtime_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StopRequest::release_runtime_id() {
  // @@protoc_insertion_point(field_release:helixrt.StopRequest.runtime_id)
  return runtime_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StopRequest::set_allocated_runtime_id(std::string* runtime_id) {
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), runtime_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helixrt.StopRequest.runtime_id)
}
inline std::string* StopRequest::unsafe_arena_release_runtime_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helixrt.StopRequest.runtime_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return runtime_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StopRequest::unsafe_arena_set_allocated_runtime_id(
    std::string* runtime_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      runtime_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helixrt.StopRequest.runtime_id)
}

// -------------------------------------------------------------------

// StreamRequest

// string runtime_id = 1;
inline void StreamRequest::clear_runtime_id() {
  runtime_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StreamRequest::runtime_id() const {
  // @@protoc_insertion_point(field_get:helixrt.StreamRequest.runtime_id)
  return _internal_runtime_id();
}
inline void StreamRequest::set_runtime_id(const std::string& value) {
  _internal_set_runtime_id(value);
  // @@protoc_insertion_point(field_set:helixrt.StreamRequest.runtime_id)
}
inline std::string* StreamRequest::mutable_runtime_id() {
  // @@protoc_insertion_point(field_mutable:helixrt.StreamRequest.runtime_id)
  return _internal_mutable_runtime_id();
}
inline const std::string& StreamRequest::_internal_runtime_id() const {
  return runtime_id_.Get();
}
inline void StreamRequest::_internal_set_runtime_id(const std::string& value) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StreamRequest::set_runtime_id(std::string&& value) {
  
  runtime_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helixrt.StreamRequest.runtime_id)
}
inline void StreamRequest::set_runtime_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helixrt.StreamRequest.runtime_id)
}
inline void StreamRequest::set_runtime_id(const char* value,
    size_t size) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helixrt.StreamRequest.runtime_id)
}
inline std::string* StreamRequest::_internal_mutable_runtime_id() {
  
  return runtime_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StreamRequest::release_runtime_id() {
  // @@protoc_insertion_point(field_release:helixrt.StreamRequest.runtime_id)
  return runtime_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StreamRequest::set_allocated_runtime_id(std::string* runtime_id) {
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), runtime_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helixrt.StreamRequest.runtime_id)
}
inline std::string* StreamRequest::unsafe_arena_release_runtime_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helixrt.StreamRequest.runtime_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return runtime_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StreamRequest::unsafe_arena_set_allocated_runtime_id(
    std::string* runtime_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      runtime_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helixrt.StreamRequest.runtime_id)
}

// -------------------------------------------------------------------

// StatusResponse

// bool success = 1;
inline void StatusResponse::clear_success() {
  success_ = false;
}
inline bool StatusResponse::_internal_success() const {
  return success_;
}
inline bool StatusResponse::success() const {
  // @@protoc_insertion_point(field_get:helixrt.StatusResponse.success)
  return _internal_success();
}
inline void StatusResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void StatusResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:helixrt.StatusResponse.success)
}

// string message = 2;
inline void StatusResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StatusResponse::message() const {
  // @@protoc_insertion_point(field_get:helixrt.StatusResponse.message)
  return _internal_message();
}
inline void StatusResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:helixrt.StatusResponse.message)
}
inline std::string* StatusResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:helixrt.StatusResponse.message)
  return _internal_mutable_message();
}
inline const std::string& StatusResponse::_internal_message() const {
  return message_.Get();
}
inline void StatusResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StatusResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helixrt.StatusResponse.message)
}
inline void StatusResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helixrt.StatusResponse.message)
}
inline void StatusResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helixrt.StatusResponse.message)
}
inline std::string* StatusResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StatusResponse::release_message() {
  // @@protoc_insertion_point(field_release:helixrt.StatusResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StatusResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helixrt.StatusResponse.message)
}
inline std::string* StatusResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helixrt.StatusResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StatusResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helixrt.StatusResponse.message)
}

// -------------------------------------------------------------------

// RuntimeMetrics

// string runtime_id = 1;
inline void RuntimeMetrics::clear_runtime_id() {
  runtime_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RuntimeMetrics::runtime_id() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.runtime_id)
  return _internal_runtime_id();
}
inline void RuntimeMetrics::set_runtime_id(const std::string& value) {
  _internal_set_runtime_id(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.runtime_id)
}
inline std::string* RuntimeMetrics::mutable_runtime_id() {
  // @@protoc_insertion_point(field_mutable:helixrt.RuntimeMetrics.runtime_id)
  return _internal_mutable_runtime_id();
}
inline const std::string& RuntimeMetrics::_internal_runtime_id() const {
  return runtime_id_.Get();
}
inline void RuntimeMetrics::_internal_set_runtime_id(const std::string& value) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RuntimeMetrics::set_runtime_id(std::string&& value) {
  
  runtime_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:helixrt.RuntimeMetrics.runtime_id)
}
inline void RuntimeMetrics::set_runtime_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:helixrt.RuntimeMetrics.runtime_id)
}
inline void RuntimeMetrics::set_runtime_id(const char* value,
    size_t size) {
  
  runtime_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:helixrt.RuntimeMetrics.runtime_id)
}
inline std::string* RuntimeMetrics::_internal_mutable_runtime_id() {
  
  return runtime_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RuntimeMetrics::release_runtime_id() {
  // @@protoc_insertion_point(field_release:helixrt.RuntimeMetrics.runtime_id)
  return runtime_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RuntimeMetrics::set_allocated_runtime_id(std::string* runtime_id) {
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), runtime_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:helixrt.RuntimeMetrics.runtime_id)
}
inline std::string* RuntimeMetrics::unsafe_arena_release_runtime_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:helixrt.RuntimeMetrics.runtime_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return runtime_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RuntimeMetrics::unsafe_arena_set_allocated_runtime_id(
    std::string* runtime_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (runtime_id != nullptr) {
    
  } else {
    
  }
  runtime_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      runtime_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:helixrt.RuntimeMetrics.runtime_id)
}

// int32 active_threads = 2;
inline void RuntimeMetrics::clear_active_threads() {
  active_threads_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RuntimeMetrics::_internal_active_threads() const {
  return active_threads_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RuntimeMetrics::active_threads() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.active_threads)
  return _internal_active_threads();
}
inline void RuntimeMetrics::_internal_set_active_threads(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  active_threads_ = value;
}
inline void RuntimeMetrics::set_active_threads(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_active_threads(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.active_threads)
}

// double throughput = 3;
inline void RuntimeMetrics::clear_throughput() {
  throughput_ = 0;
}
inline double RuntimeMetrics::_internal_throughput() const {
  return throughput_;
}
inline double RuntimeMetrics::throughput() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.throughput)
  return _internal_throughput();
}
inline void RuntimeMetrics::_internal_set_throughput(double value) {
  
  throughput_ = value;
}
inline void RuntimeMetrics::set_throughput(double value) {
  _internal_set_throughput(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.throughput)
}

// double latency = 4;
inline void RuntimeMetrics::clear_latency() {
  latency_ = 0;
}
inline double RuntimeMetrics::_internal_latency() const {
  return latency_;
}
inline double RuntimeMetrics::latency() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.latency)
  return _internal_latency();
}
inline void RuntimeMetrics::_internal_set_latency(double value) {
  
  latency_ = value;
}
inline void RuntimeMetrics::set_latency(double value) {
  _internal_set_latency(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.latency)
}

// double cpu_usage = 5;
inline void RuntimeMetrics::clear_cpu_usage() {
  cpu_usage_ = 0;
}
inline double RuntimeMetrics::_internal_cpu_usage() const {
  return cpu_usage_;
}
inline double RuntimeMetrics::cpu_usage() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.cpu_usage)
  return _internal_cpu_usage();
}
inline void RuntimeMetrics::_internal_set_cpu_usage(double value) {
  
  cpu_usage_ = value;
}
inline void RuntimeMetrics::set_cpu_usage(double value) {
  _internal_set_cpu_usage(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.cpu_usage)
}

// int64 timestamp = 6;
inline void RuntimeMetrics::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RuntimeMetrics::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RuntimeMetrics::timestamp() const {
  // @@protoc_insertion_point(field_get:helixrt.RuntimeMetrics.timestamp)
  return _internal_timestamp();
}
inline void RuntimeMetrics::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void RuntimeMetrics::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:helixrt.RuntimeMetrics.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace helixrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_runtime_2eproto
