// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime.proto
#ifndef GRPC_runtime_2eproto__INCLUDED
#define GRPC_runtime_2eproto__INCLUDED

#include "runtime.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace helixrt {

class RuntimeService final {
 public:
  static constexpr char const* service_full_name() {
    return "helixrt.RuntimeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::helixrt::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>> AsyncStartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>>(AsyncStartRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>> PrepareAsyncStartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>>(PrepareAsyncStartRuntimeRaw(context, request, cq));
    }
    virtual ::grpc::Status StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::helixrt::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>> AsyncStopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>>(AsyncStopRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>> PrepareAsyncStopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>>(PrepareAsyncStopRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::helixrt::RuntimeMetrics>> StreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::helixrt::RuntimeMetrics>>(StreamMetricsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>> AsyncStreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>>(AsyncStreamMetricsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>> PrepareAsyncStreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>>(PrepareAsyncStreamMetricsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamMetrics(::grpc::ClientContext* context, ::helixrt::StreamRequest* request, ::grpc::ClientReadReactor< ::helixrt::RuntimeMetrics>* reactor) = 0;
      #else
      virtual void StreamMetrics(::grpc::ClientContext* context, ::helixrt::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::helixrt::RuntimeMetrics>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>* AsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>* PrepareAsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>* AsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helixrt::StatusResponse>* PrepareAsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::helixrt::RuntimeMetrics>* StreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>* AsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helixrt::RuntimeMetrics>* PrepareAsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::helixrt::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>> AsyncStartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>>(AsyncStartRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>> PrepareAsyncStartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>>(PrepareAsyncStartRuntimeRaw(context, request, cq));
    }
    ::grpc::Status StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::helixrt::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>> AsyncStopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>>(AsyncStopRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>> PrepareAsyncStopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>>(PrepareAsyncStopRuntimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::helixrt::RuntimeMetrics>> StreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::helixrt::RuntimeMetrics>>(StreamMetricsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>> AsyncStreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>>(AsyncStreamMetricsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>> PrepareAsyncStreamMetrics(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>>(PrepareAsyncStreamMetricsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartRuntime(::grpc::ClientContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StartRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StopRuntime(::grpc::ClientContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void StopRuntime(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helixrt::StatusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamMetrics(::grpc::ClientContext* context, ::helixrt::StreamRequest* request, ::grpc::ClientReadReactor< ::helixrt::RuntimeMetrics>* reactor) override;
      #else
      void StreamMetrics(::grpc::ClientContext* context, ::helixrt::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::helixrt::RuntimeMetrics>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* AsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* PrepareAsyncStartRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* AsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helixrt::StatusResponse>* PrepareAsyncStopRuntimeRaw(::grpc::ClientContext* context, const ::helixrt::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::helixrt::RuntimeMetrics>* StreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>* AsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::helixrt::RuntimeMetrics>* PrepareAsyncStreamMetricsRaw(::grpc::ClientContext* context, const ::helixrt::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartRuntime_;
    const ::grpc::internal::RpcMethod rpcmethod_StopRuntime_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamMetrics_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartRuntime(::grpc::ServerContext* context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response);
    virtual ::grpc::Status StopRuntime(::grpc::ServerContext* context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response);
    virtual ::grpc::Status StreamMetrics(::grpc::ServerContext* context, const ::helixrt::StreamRequest* request, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartRuntime() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartRuntime(::grpc::ServerContext* context, ::helixrt::StartRequest* request, ::grpc::ServerAsyncResponseWriter< ::helixrt::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopRuntime() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopRuntime(::grpc::ServerContext* context, ::helixrt::StopRequest* request, ::grpc::ServerAsyncResponseWriter< ::helixrt::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamMetrics() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMetrics(::grpc::ServerContext* context, ::helixrt::StreamRequest* request, ::grpc::ServerAsyncWriter< ::helixrt::RuntimeMetrics>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartRuntime<WithAsyncMethod_StopRuntime<WithAsyncMethod_StreamMetrics<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StartRuntime() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::helixrt::StartRequest, ::helixrt::StatusResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::helixrt::StartRequest* request, ::helixrt::StatusResponse* response) { return this->StartRuntime(context, request, response); }));}
    void SetMessageAllocatorFor_StartRuntime(
        ::grpc::experimental::MessageAllocator< ::helixrt::StartRequest, ::helixrt::StatusResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::helixrt::StartRequest, ::helixrt::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartRuntime(
      ::grpc::CallbackServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartRuntime(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StopRuntime() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::helixrt::StopRequest, ::helixrt::StatusResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::helixrt::StopRequest* request, ::helixrt::StatusResponse* response) { return this->StopRuntime(context, request, response); }));}
    void SetMessageAllocatorFor_StopRuntime(
        ::grpc::experimental::MessageAllocator< ::helixrt::StopRequest, ::helixrt::StatusResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::helixrt::StopRequest, ::helixrt::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StopRuntime(
      ::grpc::CallbackServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StopRuntime(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamMetrics() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::helixrt::StreamRequest, ::helixrt::RuntimeMetrics>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::helixrt::StreamRequest* request) { return this->StreamMetrics(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::helixrt::RuntimeMetrics>* StreamMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::helixrt::RuntimeMetrics>* StreamMetrics(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StartRuntime<ExperimentalWithCallbackMethod_StopRuntime<ExperimentalWithCallbackMethod_StreamMetrics<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StartRuntime<ExperimentalWithCallbackMethod_StopRuntime<ExperimentalWithCallbackMethod_StreamMetrics<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartRuntime() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopRuntime() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamMetrics() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartRuntime() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartRuntime(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopRuntime() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopRuntime(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamMetrics() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamMetrics(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StartRuntime() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartRuntime(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StartRuntime(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StartRuntime(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StopRuntime() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopRuntime(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* StopRuntime(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* StopRuntime(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamMetrics() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->StreamMetrics(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* StreamMetrics(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartRuntime() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helixrt::StartRequest, ::helixrt::StatusResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::helixrt::StartRequest, ::helixrt::StatusResponse>* streamer) {
                       return this->StreamedStartRuntime(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StartRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartRuntime(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helixrt::StartRequest,::helixrt::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopRuntime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopRuntime() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helixrt::StopRequest, ::helixrt::StatusResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::helixrt::StopRequest, ::helixrt::StatusResponse>* streamer) {
                       return this->StreamedStopRuntime(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopRuntime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopRuntime(::grpc::ServerContext* /*context*/, const ::helixrt::StopRequest* /*request*/, ::helixrt::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopRuntime(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helixrt::StopRequest,::helixrt::StatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartRuntime<WithStreamedUnaryMethod_StopRuntime<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamMetrics() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::helixrt::StreamRequest, ::helixrt::RuntimeMetrics>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::helixrt::StreamRequest, ::helixrt::RuntimeMetrics>* streamer) {
                       return this->StreamedStreamMetrics(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamMetrics(::grpc::ServerContext* /*context*/, const ::helixrt::StreamRequest* /*request*/, ::grpc::ServerWriter< ::helixrt::RuntimeMetrics>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamMetrics(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::helixrt::StreamRequest,::helixrt::RuntimeMetrics>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamMetrics<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartRuntime<WithStreamedUnaryMethod_StopRuntime<WithSplitStreamingMethod_StreamMetrics<Service > > > StreamedService;
};

}  // namespace helixrt


#endif  // GRPC_runtime_2eproto__INCLUDED
